root: true

env:
  es6: true

globals:
  wx: readonly
  getApp: readonly
  App: readonly
  Page: readonly
  Component: readonly

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended

plugins:
  - "@typescript-eslint"
  - import

parserOptions:
  parser: "@typescript-eslint/parser"
  project:
    - "./tsconfig.eslint.json"

ignorePatterns:
  - coverage/
  - demo/**/*.js
  - lib/
  - node_modules/

rules:
  "@typescript-eslint/ban-types":
    - warn
    - extendDefaults: true
      types:
        "{}": false
        Function: false

  "@typescript-eslint/ban-ts-comment": off

  "@typescript-eslint/consistent-type-imports": warn

  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowHigherOrderFunctions: true
      allowDirectConstAssertionInArrowFunctions: true
      allowTypedFunctionExpressions: true

  "@typescript-eslint/naming-convention":
    - warn
    - selector: default
      format:
        - camelCase
      leadingUnderscore: allowSingleOrDouble
      trailingUnderscore: allow

    - selector:
        - variable
      format:
        - camelCase
        - PascalCase
        - UPPER_CASE
      leadingUnderscore: allowSingleOrDouble
      trailingUnderscore: allowSingleOrDouble

    - selector:
        - parameter
      format:
        - camelCase
        - PascalCase
      leadingUnderscore: allow
      trailingUnderscore: allow

    - selector:
        - property
      format: null
      # allow locales path like `/zh/`, alias starting with `@` and css property like `line-width`
      filter: (^/$|^/.*/$|^@|^[a-z]+(?:-[a-z]+)*?$)
      leadingUnderscore: allow
      trailingUnderscore: allow

    - selector:
        - property
      format:
        - camelCase
        - PascalCase
        - UPPER_CASE
      leadingUnderscore: allow
      trailingUnderscore: allow

    - selector: import
      format:
        - PascalCase
        - camelCase

    - selector: typeLike
      format:
        - PascalCase

  "@typescript-eslint/no-explicit-any":
    - warn
    - ignoreRestArgs: true

  "@typescript-eslint/no-non-null-assertion":
    - off

  "@typescript-eslint/no-unsafe-enum-comparison":
    - off

  "@typescript-eslint/no-unsafe-member-access":
    - warn

  curly:
    - error
    - multi
    - consistent

  import/consistent-type-specifier-style:
    - error
    - prefer-top-level

  import/first:
    - error

  import/newline-after-import:
    - error

  import/no-commonjs:
    - error

  import/no-cycle:
    - error

  import/no-duplicates:
    - error
    - considerQueryString: true

  import/no-named-default:
    - error

  import/no-restricted-paths:
    - error
    - zones:
        - target: packages/*/src/client/**
          from: packages/*/src/node/**
        - target: packages/*/src/node/**
          from: packages/*/src/client/**

  import/order:
    - error
    - alphabetize:
        order: asc
        orderImportKind: asc
      groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
        - index
        - object
      newlines-between: always

  no-unmodified-loop-condition:
    - error

  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - const
        - let
      next:
        - "*"
    - blankLine: any
      prev:
        - const
        - let
      next:
        - const
        - let
    - blankLine: always
      prev:
        - "*"
      next:
        - return

  sort-imports:
    - error
    - allowSeparatedGroups: false
      ignoreDeclarationSort: true

overrides:
  - files:
      - "**/__tests__/**/*.{spec,test-d}.{j,t}s"
    plugins:
      - vitest
    extends:
      - plugin:vitest/recommended
    rules:
      "@typescript-eslint/no-empty-function": off
      "@typescript-eslint/no-explicit-any": off
      "@typescript-eslint/no-unsafe-assignment":
        - off
      "@typescript-eslint/no-unsafe-call":
        - off
      "@typescript-eslint/no-unsafe-member-access":
        - off

  - files:
      - "**/__tests__/**/*.test-d.ts"
    rules:
      "@typescript-eslint/unbound-method": off

  - files:
      - "vitest.config.js"
      - "rollup.config.mts"
      - "scripts/**/*.js"

    env:
      node: true

    parserOptions:
      sourceType: module
      ecmaVersion: 2020
