root: true

env:
  es6: true

globals:
  wx: readonly
  getApp: readonly
  App: readonly
  Page: readonly
  Component: readonly

extends:
  - "eslint:recommended"
  - plugin:prettier/recommended

ignorePatterns:
  - demo/**/*.js
  - lib/
  - node_modules/

overrides:
  - files:
      - "*.ts"

    extends:
      - "plugin:@typescript-eslint/eslint-recommended"
      - "plugin:@typescript-eslint/recommended"
      - "plugin:@typescript-eslint/recommended-requiring-type-checking"
      - plugin:prettier/recommended

    plugins:
      - "@typescript-eslint"

    parserOptions:
      parser: "@typescript-eslint/parser"
      project:
        - "./tsconfig.json"
        - "./tsconfig.eslint.json"

    rules:
      "@typescript-eslint/ban-types":
        - warn
        - extendDefaults: true
          types:
            "{}": false
            Function: false

      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/naming-convention":
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - parameter
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - warn
        - ignoreRestArgs: true

      "@typescript-eslint/no-unsafe-member-access":
        - warn

  - files:
      - "**/__tests__/**/*.spec.{j,t}s"

    env:
      jest: true

    rules:
      "@typescript-eslint/no-empty-function":
        - off
      "@typescript-eslint/no-explicit-any":
        - off
      "@typescript-eslint/no-unsafe-assignment":
        - off
      "@typescript-eslint/no-unsafe-call":
        - off
      "@typescript-eslint/no-unsafe-member-access":
        - off

  - files:
      - "**/__tests__/**/*.tsd.ts"

    rules:
      "@typescript-eslint/ban-ts-comment":
        - off
      "@typescript-eslint/no-empty-function":
        - off
      "@typescript-eslint/no-explicit-any":
        - off
      "@typescript-eslint/no-unsafe-assignment":
        - off
      "@typescript-eslint/no-unsafe-call":
        - off
      "@typescript-eslint/no-unsafe-member-access":
        - off
      "@typescript-eslint/unbound-method":
        - off

  - files:
      - "jest.config.js"
      - "rollup.config.js"
      - "scripts/**/*.js"

    env:
      node: true

    parserOptions:
      sourceType: module
      ecmaVersion: 11
