packages:
  - demo/
  - docs/
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  esbuild: true

configDependencies:
  pacquet: "^0.11.10"

enableGlobalVirtualStore: true

minimumReleaseAgeExclude:
  - "@oxfmt/*"
  - "@oxlint/*"
  - oxc-config-hope
  - oxfmt
  - oxlint
