packages:
  - demo/
  - docs/
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  esbuild: true

virtualStoreType: global

minimumReleaseAgeExclude:
  - "@mdit/*"
  - "@mptool/*"
  - "@mr-hope/*"
  - "@oxfmt/*"
  - "@oxlint/*"
  - "@vuepress/*"
  - "oxc-config-hope"
  - "oxfmt"
  - "oxlint"
  - "vuepress"
  - "vuepress-*"

packageExtensions:
  "@lerna-lite/version":
    peerDependencies:
      conventional-changelog-conventionalcommits: ^10.2.0
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
trustPolicyExcludePrune: true
trustPolicyIgnoreAfter: 720
