name: Build Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test on node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - "16"
          - "18"
          - "20"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Build project
        run: pnpm build

      - name: Linter test
        run: pnpm lint

      - name: Unit test
        run: pnpm test
