name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  linter-and-unit:
    name: Linter and Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          runtime: node@^24.20.0

      - name: Install deps
        run: pnpm ci

      - name: Build project
        run: pnpm run build

      - name: Linter test
        run: pnpm run lint

      - name: Unit test
        run: pnpm run test

      - name: Upload coverage
        if: ${{ !cancelled() && github.ref == 'refs/heads/main' }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results
        if: ${{ !cancelled() && github.ref == 'refs/heads/main' }}
        uses: codecov/test-results-action@v1
        with:
          file: ./coverage/test-report.junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}
